name: API Doc

on:
  push:
    branches: [libedax_sensuikan1973]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'src/'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
