name: build

on:
  pull_request:
    paths: ['src/**', 'include/**', '.github/workflows/build.yaml']
  push:
    paths: ['src/**', 'include/**', '.github/workflows/build.yaml']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false # We want results from all OSes even if one fails.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_command: make build ARCH=x86-64-v3 COMP=gcc OS=linux
          - os: windows-latest
            build_command: nmake -fnmakefile vc-x64-v3
          - os: macos-latest
            build_command: make build ARCH=armv8.5-a COMP=gcc OS=osx

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |-
        mkdir -p bin
        cd src
        ${{ matrix.build_command }}

    - uses: actions/upload-artifact@v4
      with:
        name: artifact_${{ runner.os }}
        path: bin
